// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy63wKW9UaJu6noZjWuiKN85eHIVQx0zA',
    appId: '1:754606390926:web:6e2fb91ad8ed0eac3713df',
    messagingSenderId: '754606390926',
    projectId: 'fcm-zenn',
    authDomain: 'fcm-zenn.firebaseapp.com',
    storageBucket: 'fcm-zenn.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaKT8ZlcB-JnhJTwuA3vO2ieT-DsuQnCg',
    appId: '1:754606390926:android:0e0985ba4d5da7743713df',
    messagingSenderId: '754606390926',
    projectId: 'fcm-zenn',
    storageBucket: 'fcm-zenn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3QZpmfBvtAnTZFBwpbqcquvrPDjJtipM',
    appId: '1:754606390926:ios:e72156f7181bfafd3713df',
    messagingSenderId: '754606390926',
    projectId: 'fcm-zenn',
    storageBucket: 'fcm-zenn.appspot.com',
    iosClientId: '754606390926-re6nfjqfp8qillpb8r7vc0cnino4cnbv.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3QZpmfBvtAnTZFBwpbqcquvrPDjJtipM',
    appId: '1:754606390926:ios:e72156f7181bfafd3713df',
    messagingSenderId: '754606390926',
    projectId: 'fcm-zenn',
    storageBucket: 'fcm-zenn.appspot.com',
    iosClientId: '754606390926-re6nfjqfp8qillpb8r7vc0cnino4cnbv.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseSample',
  );
}
